verbose:
	quint run twolayeredcache.qnt --invariant=strongConsistency --mbt

run:
	quint run twolayeredcache.qnt --invariant=strongConsistency

verify:
	quint verify twolayeredcache.qnt --invariant=strongConsistency --verbosity=5

quickverify:
	quint verify twolayeredcache.qnt --invariant=strongConsistency --verbosity=5 --max-steps=2

test:
	quint test twolayeredcache.qnt
