verbose:
	quint run twolayeredcache.qnt --invariant=safety --mbt

run:
	quint run twolayeredcache.qnt --invariant=safety

verify:
	quint verify twolayeredcache.qnt --invariant=safety --verbosity=5 --max-steps=10

quickverify:
	quint verify twolayeredcache.qnt --invariant=safety --verbosity=5 --max-steps=2

test:
	quint test twolayeredcache.qnt
