verbose:
	quint run twolayeredcache.qnt --invariant=strongConsistency --mbt

run:
	quint run twolayeredcache.qnt --invariant=strongConsistency

verify:
	quint verify twolayeredcache.qnt --invariant=strongConsistency

test:
	quint test twolayeredcache.qnt
