verbose:
	quint run two_layered_cache.qnt --invariant=safety --mbt

run:
	quint run two_layered_cache.qnt --invariant=safety

verify:
	quint verify two_layered_cache.qnt --invariant=safety --verbosity=5 --max-steps=15

quickverify:
	quint verify two_layered_cache.qnt --invariant=safety --verbosity=5 --max-steps=2

test:
	quint test two_layered_cache.qnt
